### ISSUE TITLE
how to solve this?

### ISSUE THREAD

**Issue by WithOrchid** [iampawan/FlutterExampleApps#13]
package:http/http.dart
That library is in a package that is not known. Maybe you forgot to mention it in your pubspec.yaml file?

**Comment by WithOrchid** [comment]
Target of URI doesn't exist: 'package:http/http.dart

**Comment by Brixto** [comment]
you are probably referring to the UI-Kit Repo, right? This PR fixes the problem, after merging to master [PR#22](https://github.com/iampawan/Flutter-UI-Kit/pull/22)
To fix for you locally: add the http dependency to your pubspec.yaml file: [install http dependency](https://pub.dartlang.org/packages/http#-installing-tab-)
