### ISSUE TITLE
How to create dynamic widgets based on json response flutter

### ISSUE THREAD

**Issue by mdzafar3194** [iampawan/FlutterExampleApps#20]
How do i design the screen as shown in the Screenshot
**Screenshot**
![image](https://user-images.githubusercontent.com/22235737/68849744-a817a780-06f8-11ea-9f8a-ea6068e71e59.png)

Here, in the screen it has option to swipe screen within the fixed content and screen are also created dynamically based on json response

Also, please help me out in creating dynamic expansiontile with multiple items as in the screenshot, and providing user to enter comments and store comment values based in each exapansiontile
Any help would be appreciated..

**Comment by SnapeDragon** [comment]
Well you can use `Tab View` and `List View` Combined and in ListView use set of widgets in column. and you can use Statefull widget and your logic to make List Expansion work!

**Comment by iampawan** [comment]
You can prefix type of widgets you want to create based on your response
