### ISSUE TITLE
how  to run in android?

### ISSUE THREAD

**Issue by NeighborhoodCoding** [iampawan/FlutterExampleApps#31]
there is no run method..

**Comment by Ankitkj1999** [comment]
Can you please explain the issue?

**Comment by kreeztoph** [comment]
Please explain better

**Comment by kreeztoph** [comment]
If you are using vs code or android studio, please specify.
Thank you.

**Comment by Ankitkj1999** [comment]
I am using VS code!!

**Comment by sandlib** [comment]
Unless there is any main method , You can't run it on any device.

**Comment by Ankitkj1999** [comment]
The main function is important for every flutter app that we create, we need to tell flutter from where the code execution should start as we do in every other programming language. 
If you are interested in knowing what else we can do with the main function you can follow this link.
[Flutter Main  function](https://medium.com/flutter-community/the-main-function-in-flutter-24408cf9c951#:~:text=Is%20there%20an%20easier%20solution,file%20to%20run%20our%20app.)

**Comment by Ankitkj1999** [comment]
There is no run method because there is no app for you to run. This repository is used as the documentation only. You can find the link to the specific repo in the **read.md** below.

**Comment by shubham8170** [comment]
connect your android device and just run it .it will show some debug message
