### ISSUE TITLE
pubspec.yaml find not found

### ISSUE THREAD

**Issue by saksham-gt** [iampawan/FlutterExampleApps#48]
I'm unable to find pubspec.yaml file of this project. And, also (idk why I did this)  I tried to copy pubspec.yaml file from other my other projects but it showed 
**"Target file "lib/main.dart" not found."**

Please help how do I overcome this pubspec.yaml problem?

**Comment by Roy-Tuhin** [comment]
pubspec.yaml file will automatically create when you initiate your flutter project. If just wanna copy-paste the code then, go-to the "lib" folder and paste all the code file.

**Comment by Victorcassiano** [comment]
Don't forget to use flutter pub get
