### ISSUE TITLE
How to create a centre method in flutter?

### ISSUE THREAD

**Issue by Projectroy1** [iampawan/FlutterExampleApps#65]
I am stuck in between because of this error.

**Comment by uemuki** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到，我将尽快给您回复。

**Comment by Projectroy1** [comment]
> I am stuck in between because of this error.

![IMG_20220906_124109.jpg](https://user-images.githubusercontent.com/112929599/188569857-dbd11a8a-14e1-4d66-907f-06ef62ec8f7a.jpg) How to create centre method in flutter.

**Comment by JoDeveloper** [comment]
> > I am stuck in between because of this error.
> 
> ![IMG_20220906_124109.jpg](https://user-images.githubusercontent.com/112929599/188569857-dbd11a8a-14e1-4d66-907f-06ef62ec8f7a.jpg) How to create centre method in flutter.

you have a typo ```Center``` not ```Centere```

**Comment by Projectroy1** [comment]
> > > I am stuck in between because of this error.
> > 
> > ![IMG_20220906_124109.jpg](https://user-images.githubusercontent.com/112929599/188569857-dbd11a8a-14e1-4d66-907f-06ef62ec8f7a.jpg) How to create centre method in flutter.
> 
> you have a type ```Center``` not ```Centere```

Sorry my mistake. And a really silly mistake. Appreciate your reply.

**Comment by Eze6266** [comment]
What exactly is your issue?

**Comment by JoDeveloper** [comment]
> > > > I am stuck in between because of this error.
> > > 
> > > 
> > > ![IMG_20220906_124109.jpg](https://user-images.githubusercontent.com/112929599/188569857-dbd11a8a-14e1-4d66-907f-06ef62ec8f7a.jpg) How to create centre method in flutter.
> > 
> > 
> > you have a type `Center` not `Centere`
> 
> Sorry my mistake. And a really silly mistake. Appreciate your reply.

you can close the issue 😇
